### ISSUE TITLE
Invalid HTML: forms reuse id names

### ISSUE THREAD

**Issue by puffnfresh** [slamdata/purescript-markdown#15]
```markdown
name = ________ (default)

name = ________ (default)
```

Generates:

```html
<p><label>name<input type="text" id="name" name="name"></label></p>
<p><label>name<input type="text" id="name" name="name"></label></p>
```

Either the input or the output is wrong. I think we need to either detect the error or generate different output.

**Comment by jdegoes** [comment]
It's unMarkdown-like to generate errors (i.e. fail parsing), but this could at least be a warning if we supported such things, and a good example of information we'd want to convey to the user after successful evaluation of a Markdown block in the case that it succeeds.

The options otherwise are (a) ignoring either the first or second one, because they both have the same names, or (b) generating a unique suffix for the second one. 

In most cases of overlapping names, the fields will probably be widely separated, which is why the user re-used the name without knowing. I think the most surprising thing would be to *not* generate HTML for the 2nd one. This would alert the user to a problem ("Why isn't my form element showing?"), which would then cause them to dig around for more details, thus uncovering the problem. i.e. it's "fail earlier". The alternative of generating a unique suffix postpones the problem to later, because the user can see their form elements, but then when they try to write a query which references a variable, it has the wrong value, which is something they may or may not notice, depending on what they're trying to do.

**Comment by garyb** [comment]
There are currently a few `id` related problems, the labels for checkboxes and radio buttons are also a mess because each option is given the same id (clicking any label triggers the same option - or no option, it depends on browser).

Do we care about `id`s, or are `name`s more important? From a form point of view, `name`s are the things that are used for field names when sending to the server, so if we just generate all our `id`s it gets around this and is also the "proper" thing to do - in the radio button case you give all the options the same `name` but different `id`s. If you have multiple text inputs with the same name, then both values get sent in the GET or POST request for the form... that doesn't really help us out in SlamData though.

While I'm at it, should Halogen-HTML-rendering even be handled in this library? It seems like a strange dependency to pull in if someone wants to use markdown.

**Comment by jdegoes** [comment]
Yeah, `id`s are an implementation issue, we only care about what the server sees, which must be predictably related to the form itself.

> While I'm at it, should Halogen-HTML-rendering even be handled in this library? It seems like a strange dependency to pull in if someone wants to use markdown.

Likely this should be `purescript-markdown-halogen`, which would depend on both halogen and markdown.

**Comment by garyb** [comment]
Can you make a repo for that? I'll do the split while I'm working on these enhancements and fixes.

**Comment by garyb** [comment]
Thanks!

**Comment by garyb** [comment]
Fixed in https://github.com/slamdata/purescript-markdown-halogen/commit/9bb0d19bd011d8e7c5812f3e78b689d3f4ff5240
