### ISSUE TITLE
warn on invalid default values

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-markdown#33]
The parser should always succeed, but perhaps output a `Tuple` or something with warnings for invalid default values:

- Invalid date formats (should be `YYYY-MM-DD`)
- Invalid time formats (should be `HH:MM`)
- Invalid date/time formats (should be `YYYY-MM-DDTHH:MM`)
- Non-numeric default values for `#___`
- Dropdown values that are not present in the specified set (e.g. `{BOS, SFO, NYC} (XXX)`)

**Comment by jdegoes** [comment]
`WriterT` :smile:

**Comment by garyb** [comment]
Or that! :+1:

**Comment by jonsterling** [comment]
So is it decided that we want to put the whole parser into `WriterT`? I just want to make sure, because it is a bit of an invasive API change, and would likely require a fair amount of restructuring of unrelated stuff.

Another possible technique would be to separate the validation of input from the parsing of input, and to just have a pass `Block -> Writer (Array String) Block`. There may be implications as far as source positions are concerned, though...

@garyb @jdegoes

**Comment by jdegoes** [comment]
I prefer separating parsing from analysis (no WriterT), assuming we can preserve all the information we need in the parse phase.
